name: Build CrownDrip Executor

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore solution
        shell: cmd
        run: |
          msbuild Crowndrip.sln /t:Restore /p:Configuration=Release /p:Platform=x64 /p:RuntimeIdentifier=win-x64

      - name: Build solution
        shell: cmd
        run: |
          msbuild Crowndrip.sln /p:Configuration=Release /p:Platform=x64 /p:RuntimeIdentifier=win-x64 /p:GenerateDebugInformation=false

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CrownDrip-Production-Build
          path: |
            src/Crowndrip_UI/bin/x64/Release/net48/**
            x64/Release/**
